name="gate"
index=1

[server]
ip="0.0.0.0"
port=4567

[thread]
cnt = -1

[nats-core]
host="127.0.0.1"
port=4222
subs = ["all.all.id.*","gate.1.id.*"]
queues=["gate.queue.id.*"]
queue_group="gate"

[[nats--------------------------deleted]]
name="system"
host="127.0.0.1"
port=4222
subs = ["all.all.id.*","gate.1.id.*"]


[[dbs]]
ip=""
user=""
pw=""
port=""

[[dbs]]



[[modules]]
name="123"
path=""
instance_cnt = 10
