name="gate"
type=1

[server]
ip="0.0.0.0"
port=4567

[thread]
cnt = -1


[[nats]]
host="127.0.0.1"
port=4222
pubs = [""]

[[nats]]
host="127.0.0.1"
port=4222
pubs = [""]


[[dbs]]
ip=""
user=""
pw=""
port=""

[[dbs]]



[[modules]]
name="123"
path=""
instance_cnt = 10







