server_type="gate"
server_no = 1

[server]
ip="0.0.0.0"
port=4567

[thread]
cnt = -1


[[nats]]
host="127.0.0.1"
port=4222
pubs = [""]

[[nats]]
name="nats_client"
host="127.0.0.1"
port=4222
pubs = ["gate.idx1.id.*"]


[[dbs]]
ip=""
user=""
pw=""
port=""

[[dbs]]



[[modules]]
name="123"
path=""
instance_cnt = 10







