name="gate"
type=1
index=1
unique_id = "gate.1"


[server]
ip="0.0.0.0"
port=4567

[thread]
cnt = -1

[nats-core]
host="127.0.0.1"
port=4222
subs = ["all.all.id.*","gate.1.system.id.*"]
queue_sub="gate.queue.id.*"

[[nats]]
name="system"
host="127.0.0.1"
port=4222
subs = ["all.all.id.*","gate.1.system.id.*"]


[[dbs]]
ip=""
user=""
pw=""
port=""

[[dbs]]



[[modules]]
name="123"
path=""
instance_cnt = 10







